### ISSUE TITLE
Unable to run genDrumkit

### ISSUE THREAD

**Issue by githubtefo** [peter-zenk/genDrumkit#3]
**Describe the bug**
After install it, the command returns:

> Traceback (most recent call last):
>   File "/usr/bin/genDrumkit", line 4, in <module>
>     __import__('pkg_resources').run_script('genDrumkit==0.1.3', 'genDrumkit')
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 651, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1455, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/lib/python3.10/site-packages/genDrumkit-0.1.3-py3.10.egg/EGG-INFO/scripts/genDrumkit", line 13, in <module>
> ModuleNotFoundError: No module named 'gen_drum_kit'

**To Reproduce**
1. Download source code
2.  run python setup.py build
3. python sudo setup.py install
4. run genDrumkit

**Expected behavior**

**Screenshots**

**Comment by peter-zenk** [comment]
This is a known issue / missing feature:
So far the code has not been prepared for integration using python setup.py.

**Work-around**: 
# get code (git or download and unpack zip)
% cd .../src
% chmod +x genDrumkit 
% ./genDrumkit --help

**Comment by githubtefo** [comment]
Oohh I see. So, how can I uninstall it/ undo setup.py?

Thanks!

**Comment by peter-zenk** [comment]
To be honest, no idea at the moment. 
Probably best option is to find it in the file system and wipe it manually with "sudo rm -r" (use with care!!!)
On the other hand, it should not take to much disk space ...

Will take some time to implement proper installation due to current lack of knowledge on my side. :-(

**Comment by peter-zenk** [comment]
disabled existing setup (which was incomplete) so no-one else will run into the problem

**Comment by githubtefo** [comment]
> Probably best option is to find it in the file system and wipe it manually with "sudo rm -r" (use with care!!!)

this did the job!
> ❯ sudo pip uninstall genDrumkit 
> Found existing installation: genDrumkit 0.1.3
> Uninstalling genDrumkit-0.1.3:
>   Would remove:
>     /usr/bin/genDrumkit
>     /usr/lib/python3.10/site-packages/genDrumkit-0.1.3-py3.10.egg
> Proceed (y/n)? y
>   Successfully uninstalled genDrumkit-0.1.3
> 

Great! Thanks! Will try it directly from the downloaded dir and reach you if I have more questions!
Thanks for your help and the package as well!

**Comment by peter-zenk** [comment]
Ah, thanks for the info! Learned something new today

**Comment by peter-zenk** [comment]
... and keep in mind, taking into consideration the lack of specs (-> reverse engineering), the complexity of the task, and my certainly limited knowledge I would expect further issues. Though I did run it on all Hydrogen kits I have around.
It might be necessary to tweak the generated xml files with an editor to make it run on Drumgizmo
