### ISSUE TITLE
Version number in release title field?

### ISSUE THREAD

**Issue by mxmilkiib** [peter-zenk/genDrumkit#4]
**Is your feature request related to a problem? Please describe.**
When items on https://github.com/monocasual/giada/releases are given a title, that is carried through to https://github.com/peter-zenk/genDrumkit/releases.atom which makes it impossible to parse the version number from titles.

**Describe the solution you'd like**
Release titles prefixed with version numbers, like "0.1.4 - disable setup.py"

**Additional context**
This is for https://libreav.org

**Comment by peter-zenk** [comment]
release title modified
